### ISSUE TITLE
Definir el tema de la charla inicial

### ISSUE THREAD

**Issue by ancorgs** [ancorgs/leap_15.1_gran_canaria#3]
El plan es empezar con una especie de "keynote" (perdón por el anglicismo) para todos los asistentes. Habrá que decidir el tema y prepararla un poco

**Comment by dgdavid** [comment]
>  (perdón por el anglicismo)

_presentación_ puede ser el término adecuado en español, ¿no? :thinking:

**Comment by ancorgs** [comment]
Creo que deberíamos basarnos en la charla que Ludwig hizo en la GNU Health y que está [aquí](https://github.com/ancorgs/leap_15.1_gran_canaria/blob/master/presentaciones/antiguas/20181123_gnuhealthcon.odp). Damos tres pinceladas super rápidas sobre software libre, explicamos que es Linux por si hay algún despistado, presentamos el proyecto openSUSE y finalmente Leap vs TW (al fin y al cabo Leap 15.1 es la excusa de todo).

Como coletilla, presentamos el resto de las charlas/talleres y los mandamos para el aulario a que se repartan según intereses.

¿Hace?

**Comment by dgdavid** [comment]
Áncor, creo que es justo felicitarte por...

¡ajustarte al tiempo de la charla! :stuck_out_tongue_winking_eye: 

Ahora en serio, fue una presentación bastante amena, la verdad. _Con gancho_  :smile: 

¡Gracias!

**Comment by teclator** [comment]
@dgdavid está claro que es un auténtico showman :P
