### ISSUE TITLE
Definir los talleres/charlas para dar en el aulario

### ISSUE THREAD

**Issue by ancorgs** [ancorgs/leap_15.1_gran_canaria#4]
La idea es simultanear en todo momento un par de talleres o de charlas que puedan ser interesantes. Hay que preparar un programa.

**Comment by imobachgs** [comment]
A bote pronto, y sin pensarlo mucho, se me ocurren algunos temas que podría comprometerme a preparar (o ayudar):

* Sistemas de gestión de configuraciones (Salt, en este caso).
* Containers (docker, podman, whatever) en general. Podría ser interesante explicarles cómo usarlos para desarrollo, aunque supongo que eso es algo que ya hacen... ¿o no?
* Empaquetar software.

Mis 2 céntimos de euro :)

**Comment by ancorgs** [comment]
Por mi parte, yo di en El Rincón una charla junto a Christian que podríamos reciclar, subiré las transparencias (lo hicimos en inglés)

También estaría bien reciclar la charla de Ludwig dió sobre openSUSE en la GNU Health Con. Se la pido.

En la cosa esa del software craftmanship improvisé una sobre cómo usamos integración continua (OBS+openQA+staging+...) para hacer openSUSE que diría que gustó bastante para ser improvisada. No creo que tenga nada de material (hice unas notas en papel y lo enseñé todo en un navegador), pero creo que gustó bastante.

**Comment by ancorgs** [comment]
> Por mi parte, yo di en El Rincón una charla junto a Christian que podríamos reciclar, subiré las transparencias (lo hicimos en inglés)

Parece que las transparencias están en español. No incluyen muchas notas, pero las subí a `presentaciones/antiguas`

> También estaría bien reciclar la charla de Ludwig dió sobre openSUSE en la GNU Health Con. Se la pido.

También la subí a ese directorio.
 
> En la cosa esa del software craftmanship improvisé una sobre cómo usamos integración continua (OBS+openQA+staging+...) para hacer openSUSE que diría que gustó bastante para ser improvisada. No creo que tenga nada de material (hice unas notas en papel y lo enseñé todo en un navegador), pero creo que gustó bastante.

Efectivamente, no encontré nada. Puedo re-prepararla.

**Comment by ancorgs** [comment]
La gente de Red Hat tiene una charla ya preparada orientada a los alumnos de administración de sistemas. El tema es algo así como: "Una introducción a contenedores, la nube y esas yerbas para administradores de la vieja escuela".

Yo empiezo a vislumbrar dos "tracks", una para administradores y otra para desarrolladores. Una tercera para "público generalista" estaría bien si surge contenido.

Para desarrolladores (que se haya mencionado):

- Ganarse la vida desarrollando software libre
- Continuous Delivery en openSUSE (OBS+openQA+staging)
- Usando containers y esas yerbas para desarrollo

Para administradores:

- Sistemas de gestión de configuraciones (Salt, en este caso)
- Contenedores, nubes y demás "modernidades"
- Alguna demo vistosa para complementar la anterior (creo que Xabi tiene algo medio preparado)

Si surge más contenido, muchísimo mejor, pero con eso y una charla general de apertura para todos (ver #3), lo tenemos bastante encaminado.

**Comment by rtorrero** [comment]
Yo puedo pillar algo de lo que se ha planteado de containers o presentar algo sobre preparación de entornos de desarrollo en Leap o TW para experimentación con redes usando:
 - VMs
 - linux bridges o OVS 
 - algún switch / router corriendo OpenWRT

**Comment by rtorrero** [comment]
Por cierto, tenemos claro el formato de la charlas / talleres? (duración, nivel técnico, contenido práctico o teórico, ...)

**Comment by dgdavid** [comment]
Se me ocurre que, en caso de que no estén usando ninguno aún, podríamos proponer una pequeña introducción a Git como sistema de control de versiones.

**Comment by dgdavid** [comment]
Finalmente, las charlas fueron definidas en 

https://github.com/ancorgs/leap_15.1_gran_canaria/blob/master/info_para_el_cartel.md

Y publicadas en la página del IES El Rincón

http://www3.gobiernodecanarias.org/medusa/edublog/ieselrincon/2019/06/04/jornadas-sobre-linux-y-software-libre/
