### ISSUE TITLE
Conseguir merchandising

### ISSUE THREAD

**Issue by ancorgs** [ancorgs/leap_15.1_gran_canaria#5]
No hay fiesta sin merchandising. Como mínimo habría que decorar el aulario un poco. Idealmente también tener merchandising para repartir. Podemos intentar que nos lo envíen desde Madrid, que nos lo envíen desde Nuremberg o aprovechar nuestra excursión a la openSUSE Conference para venir cargados. Pero hay que organizarlo en cualquier caso.

**Comment by ancorgs** [comment]
Le escribí a Lukas y Douglas a ver qué se puede hacer por esa banda. Yo creo que el mejor plan es traernos una caja/maleta con cosas cuando regresemos de la openSUSE Conference.

**Comment by dgdavid** [comment]
> Yo creo que el mejor plan es traernos una caja/maleta con cosas cuando regresemos de la openSUSE Conference.

Estoy de acuerdo, pero no por ello dejaría de pedirle también a Madrid. Que las camisetas de _SuperSUSE_ están molonas :wink:

**Comment by ancorgs** [comment]
> Le escribí a Lukas y Douglas a ver qué se puede hacer por esa banda. Yo creo que el mejor plan es traernos una caja/maleta con cosas cuando regresemos de la openSUSE Conference.

Me respondió Douglas. Dice que debería haber cosillas por ahí para traernos en el viaje de vuelta. Y que si encuentra algo demasiado grande siempre puede enviárnoslo por correo (se ve que no sabe cómo funciona aquí).

Por otro lado, sé de buena tinta que Luis el de Gnu Health tiene un stand de openSUSE plegable que usa en las Gnu Health Con. Si lo necesitamos seguro que se lo podemos pedir.
