### ISSUE TITLE
Conseguir algo de comer/beber

### ISSUE THREAD

**Issue by ancorgs** [ancorgs/leap_15.1_gran_canaria#6]
Se supone que en cierto modo es una fiesta, habría que ofrecer algún refrigerio. Idealmente cervezas openSUSE. Pero si eso es complicado, cualquier otra cosa.

**Comment by ancorgs** [comment]
Le escribí a Lukas y Douglas a ver qué se puede hacer por esa banda.

**Comment by rtorrero** [comment]
Tiene más sentido traer comida al sitio o llegar a algún acuerdo con alguno de los sitios que hay en las arenas para comer todos ahí? Veo ventajas para ambas opciones, pero habría que ver presupuestos y cantidad de gente que estimamos que vaya a atender

**Comment by ancorgs** [comment]
Douglas me dijo que no podía enviar cerveza openSUSE (había que intentarlo) pero que podíamos cargar cosillas de comer y beber al "cost center" de openSUSE. :+1:

**Comment by dgdavid** [comment]
¡Gracias @DavidKang por la gestión! :wink:
